import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header>
          <ul className="p-4 flex flex-row gap-2 border-b-black border-b mb-2">
            <li>
              <a href="/animations">animations</a>
            </li>
            <li>
              <a href="/calculator">calculator</a>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
